language: java

cache:
  directories:
    - $HOME/.gradle/caches/3.4.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check --continue --stacktrace